<h1>Selecting & Filtering Data</h1>

In [1]:
import pandas as pd

<h3>Create a Sample Dataset</h3>

In [4]:
students = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Arjun", "Rogan", "Prakash", "Jothi", "Mathi", "Dinesh"],
    "Age": [22, 23, 21, 24, 22, 23],
    "Department": ["AI", "ML", "DS", "AI", "ML", "DS"],
    "Marks": [95, 88, 91, 84, 89, 76]
})

print(students)

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
1  102    Rogan   23         ML     88
2  103  Prakash   21         DS     91
3  104    Jothi   24         AI     84
4  105    Mathi   22         ML     89
5  106   Dinesh   23         DS     76

<h2>loc</h2>

loc is used to select data using labels.
    
loc = select rows/columns by their names or labels.

Syntax:

df.loc[row_label, column_name]

__Example:__

A school administrator wants to view only the student names and marks from the student database.

<h3>AI/ML Usage</h3>

Used to select required features before model training.

Select a Row

In [5]:
students.loc[2]

ID                103
Name          Prakash
Age                21
Department         DS
Marks              91
Name: 2, dtype: object

Select Specific Columns

In [8]:
students.loc[:,["Name", "Marks"]]

      Name  Marks
0    Arjun     95
1    Rogan     88
2  Prakash     91
3    Jothi     84
4    Mathi     89
5   Dinesh     76

<h2>iloc</h2>

iloc selects data using integer positions instead of labels.

Syntax:

df.iloc[row_position, column_position]

__Example:__

An HR manager wants to view the first three employees and selected columns from an employee dataset.

<h3>AI/ML Usage</h3>

Useful when column positions are known instead of column names.

In [9]:
students.iloc[0]

ID              101
Name          Arjun
Age              22
Department       AI
Marks            95
Name: 0, dtype: object

In [10]:
students.iloc[0:3, 1:4]

      Name  Age Department
0    Arjun   22         AI
1    Rogan   23         ML
2  Prakash   21         DS

<h3>Difference Between loc and iloc</h3>

loc :

Uses labels<br>
Includes end label<br>
Uses column names

iloc:

Uses integer positions<br>
Excludes end position like Python slicing<br>
Uses column numbers

<h2>Boolean Indexing</h2>

Boolean Indexing filters rows based on a condition that returns True or False.

Example:

A company wants to find employees earning more than ₹50,000.

<h3>AI/ML Usage</h3>

Used to remove unwanted records before training.

In [11]:
students["Marks"] > 90

0     True
1    False
2     True
3    False
4    False
5    False
Name: Marks, dtype: bool

Using it to filter:

In [12]:
students[students["Marks"] > 90]

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
2  103  Prakash   21         DS     91

<h2>Filtering Rows</h2>

Filtering returns only the rows that satisfy a given condition.

__Example:__

A bank filters customers who have:

<ul><li>Account balance above ₹1,00,000</li>
<li>Premium membership</li></ul>

<h3>AI/ML Usage</h3>
    
Filtering removes unnecessary data before feature engineering.

Students with Marks greater than or equal to 90.

In [13]:
students[students["Marks"] >= 90]

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
2  103  Prakash   21         DS     91

Students from AI Department.

In [14]:
students[students["Department"] == "AI"]

    ID   Name  Age Department  Marks
0  101  Arjun   22         AI     95
3  104  Jothi   24         AI     84

Multiple Conditions

In [17]:
students[(students["Department"] == "AI") & (students["Marks"] >= 80)]

    ID   Name  Age Department  Marks
0  101  Arjun   22         AI     95
3  104  Jothi   24         AI     84

<h2>query()</h2>

query() filters rows using SQL-like expressions.

It makes filtering easier to read.

Syntax:

df.query("condition")

__Example:__

A manager searches for employees with more than five years of experience and a salary above ₹60,000.

<h3>AI/ML Usage</h3>
                                                                                               
Makes complex filtering conditions easier to write and understand.

In [20]:
students.query("Department == 'AI'")

    ID   Name  Age Department  Marks
0  101  Arjun   22         AI     95
3  104  Jothi   24         AI     84

In [21]:
students.query("Marks >= 90")

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
2  103  Prakash   21         DS     91

In [25]:
students.query("Age >= 20 & Marks >= 90")

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
2  103  Prakash   21         DS     91

<h2>isin()</h2>

isin() checks whether each value exists in a given list.

Syntax:

df["column"].isin(list)

__Example:__

A company wants to view employees working only in the IT and Finance departments.

<h3>AI/ML Usage</h3>
    
Useful when filtering multiple categories.

In [28]:
students[students["Department"].isin(["AI","DS"])]

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
2  103  Prakash   21         DS     91
3  104    Jothi   24         AI     84
5  106   Dinesh   23         DS     76

<h2>between()</h2>

between() checks whether values fall within a specified range.

Syntax:

df["column"].between(start, end)

__Example:__

A teacher wants to identify students whose marks are between 85 and 92.

</h3>AI/ML Usage</h3>

Used to select records within acceptable ranges, such as age, salary, or income.

In [30]:
students[students["Marks"].between(80,90)]

    ID   Name  Age Department  Marks
1  102  Rogan   23         ML     88
3  104  Jothi   24         AI     84
4  105  Mathi   22         ML     89

<h2>Sorting Data</h2>

Sorting arranges data in ascending or descending order.

__Example:__

An online shopping website sorts products by price, rating, or popularity.

<h3>AI/ML Usage</h3>
    
Sorting helps identify top-performing records, detect anomalies, and rank prediction results.

Sort by Marks

In [31]:
students.sort_values("Marks")

    ID     Name  Age Department  Marks
5  106   Dinesh   23         DS     76
3  104    Jothi   24         AI     84
1  102    Rogan   23         ML     88
4  105    Mathi   22         ML     89
2  103  Prakash   21         DS     91
0  101    Arjun   22         AI     95

Sort in Descending Order

In [33]:
students.sort_values("Marks", ascending=False)

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
2  103  Prakash   21         DS     91
4  105    Mathi   22         ML     89
1  102    Rogan   23         ML     88
3  104    Jothi   24         AI     84
5  106   Dinesh   23         DS     76

Sort by Multiple Columns

In [35]:
students.sort_values(["Department","Marks"],ascending=[True,False])

    ID     Name  Age Department  Marks
0  101    Arjun   22         AI     95
3  104    Jothi   24         AI     84
2  103  Prakash   21         DS     91
5  106   Dinesh   23         DS     76
4  105    Mathi   22         ML     89
1  102    Rogan   23         ML     88