<h1>Data Manipulation</h1>

In [1]:
import pandas as pd

<h3>Create a Sample Dataset</h3>

In [4]:
students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104, 105, 105],
    "Name": ["Arjun", "Rogan", "Prakash", "Jothi", "Mathi", "Mathi"],
    "Age": [22, 23, 21, 24, 22, 22],
    "Department": ["AI", "ML", "DS", "AI", "ML", "ML"],
    "Marks": [95, 88, 91, 84, 89, 89]
})

print(students)

   Student_ID     Name  Age Department  Marks
0         101    Arjun   22         AI     95
1         102    Rogan   23         ML     88
2         103  Prakash   21         DS     91
3         104    Jothi   24         AI     84
4         105    Mathi   22         ML     89
5         105    Mathi   22         ML     89

<h2>Rename Columns</h2>

Renaming columns changes one or more column names in a DataFrame to make them more meaningful or consistent.

Syntax:

df.rename(columns={"old_name":"new_name"})

__Example:__

A company changes the column name Emp_ID to Employee_ID to improve readability.

<h3>AI/ML Usage</h3>
    
Meaningful column names make datasets easier to understand and document.

In [5]:
students.rename(columns={"Marks":"Scores"})

   Student_ID     Name  Age Department  Scores
0         101    Arjun   22         AI      95
1         102    Rogan   23         ML      88
2         103  Prakash   21         DS      91
3         104    Jothi   24         AI      84
4         105    Mathi   22         ML      89
5         105    Mathi   22         ML      89

<h2>Drop Rows</h2>

drop() removes one or more rows from a DataFrame.

Syntax:

df.drop(index)

__Example:__

An HR analyst removes employees who have resigned from the dataset.

<h3>AI/ML Usage</h3>

Used to remove incorrect or unnecessary records before model training.

Remove row index 3.

In [6]:
students.drop(3)

   Student_ID     Name  Age Department  Marks
0         101    Arjun   22         AI     95
1         102    Rogan   23         ML     88
2         103  Prakash   21         DS     91
4         105    Mathi   22         ML     89
5         105    Mathi   22         ML     89

Remove multiple rows.

In [9]:
students.drop([1,4])

   Student_ID     Name  Age Department  Marks
0         101    Arjun   22         AI     95
2         103  Prakash   21         DS     91
3         104    Jothi   24         AI     84
5         105    Mathi   22         ML     89

<h2>Drop Columns</h2>

Columns that are unnecessary can be removed using drop().

Syntax:

df.drop(columns=["Column_Name"])

__Example:__

A hospital removes the Patient_Address column before sharing data for research.

<h3>AI/ML Usage</h3>

Removes irrelevant features that do not contribute to model performance.

In [10]:
students.drop(columns=["Age"])

   Student_ID     Name Department  Marks
0         101    Arjun         AI     95
1         102    Rogan         ML     88
2         103  Prakash         DS     91
3         104    Jothi         AI     84
4         105    Mathi         ML     89
5         105    Mathi         ML     89

<h2>Insert Columns</h2>

insert() adds a new column at a specific position.

Syntax:

df.insert(location, column_name, values)

Example:

A school adds a Grade column after calculating marks.

<h2>AI/ML Usage</h2>

New features are often inserted after feature engineering.

In [13]:
students.insert(5, "Grade", ["A", "B", "A", "C", "B", "B"])

print(students)

   Student_ID     Name  Age Department  Marks Grades
0         101    Arjun   22         AI     95      A
1         102    Rogan   23         ML     88      B
2         103  Prakash   21         DS     91      A
3         104    Jothi   24         AI     84      C
4         105    Mathi   22         ML     89      B
5         105    Mathi   22         ML     89      B

<h2>assign()</h2>

assign() creates new columns without modifying the original DataFrame.

Syntax:

df.assign(NewColumn=values)

__Example__

A company creates a new column showing whether an employee is eligible for a bonus.

<h3>AI/ML Usage</h3>
    
Used for feature engineering while preserving the original dataset.

In [15]:
new_students = students.assign(Pass=students["Marks"]>=90)
print(new_students)

   Student_ID     Name  Age Department  Marks Grades   Pass
0         101    Arjun   22         AI     95      A   True
1         102    Rogan   23         ML     88      B  False
2         103  Prakash   21         DS     91      A   True
3         104    Jothi   24         AI     84      C  False
4         105    Mathi   22         ML     89      B  False
5         105    Mathi   22         ML     89      B  False

<h2>apply()</h2>

apply() applies a function to rows or columns.

Syntax:

df["Column"].apply(function)

__Example:__

A teacher adds grace marks to every student's score.

<h2>AI/ML Usage</h2>

Used for feature transformation and preprocessing.

In [17]:
students["Name"].apply(str.upper)

0      ARJUN
1      ROGAN
2    PRAKASH
3      JOTHI
4      MATHI
5      MATHI
Name: Name, dtype: str

<h2>map()</h2>

map() replaces or transforms values in a single column.

Syntax:

df["Column"].map(dictionary)

__Example:__

Convert department codes into department names.

<h3>AI/ML Usage</h3>

Used to encode or decode categorical values.

In [20]:
grade_map = {
    "A":"Excellent",
    "B":"Good",
    "C":"Average"
}
students["Performance"] = students["Grades"].map(grade_map)
print(students)

   Student_ID     Name  Age Department  Marks Grades Performance
0         101    Arjun   22         AI     95      A   Excellent
1         102    Rogan   23         ML     88      B        Good
2         103  Prakash   21         DS     91      A   Excellent
3         104    Jothi   24         AI     84      C     Average
4         105    Mathi   22         ML     89      B        Good
5         105    Mathi   22         ML     89      B        Good

<h2>replace()</h2>

replace() substitutes one value with another.

Syntax:

df.replace(old, new)

__Example:__

A company changes department abbreviations into full names.

<h3>AI/ML Usage</h3>
    
Used to standardize inconsistent values before model training.

In [21]:
students=students.replace({
    "Department":{
        "AI":"Artificial Intelligence",
        "ML":"Machine Learning",
        "DS":"Data Science"
    }
})

print(students)

   Student_ID     Name  Age               Department  Marks Grades Performance
0         101    Arjun   22  Artificial Intelligence     95      A   Excellent
1         102    Rogan   23         Machine Learning     88      B        Good
2         103  Prakash   21             Data Science     91      A   Excellent
3         104    Jothi   24  Artificial Intelligence     84      C     Average
4         105    Mathi   22         Machine Learning     89      B        Good
5         105    Mathi   22         Machine Learning     89      B        Good

<h2>Duplicate Handling</h2>

Duplicate handling identifies and removes repeated rows from a dataset.

<h3>Why is it Important?</h3>

Duplicate data can produce incorrect analysis and reduce machine learning model accuracy.

__Example:__

An online shopping website accidentally stores the same customer order twice. Duplicate records are removed before generating sales reports.

<h3>AI/ML Usage</h3>
    
Duplicate records can bias machine learning models. Removing duplicates improves data quality and model performance.

In [22]:
# Check Duplicates

students.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [23]:
# Count Duplicate Rows

students.duplicated().sum()

np.int64(1)

In [24]:
# Remove Duplicate Rows

students.drop_duplicates()

   Student_ID     Name  Age               Department  Marks Grades Performance
0         101    Arjun   22  Artificial Intelligence     95      A   Excellent
1         102    Rogan   23         Machine Learning     88      B        Good
2         103  Prakash   21             Data Science     91      A   Excellent
3         104    Jothi   24  Artificial Intelligence     84      C     Average
4         105    Mathi   22         Machine Learning     89      B        Good

In [25]:
# Remove Duplicates Permanently

students.drop_duplicates(inplace=True)

print(students)

   Student_ID     Name  Age               Department  Marks Grades Performance
0         101    Arjun   22  Artificial Intelligence     95      A   Excellent
1         102    Rogan   23         Machine Learning     88      B        Good
2         103  Prakash   21             Data Science     91      A   Excellent
3         104    Jothi   24  Artificial Intelligence     84      C     Average
4         105    Mathi   22         Machine Learning     89      B        Good