<h1>Grouping & Aggregation</h1>

In [2]:
import pandas as pd

In [3]:
students = pd.DataFrame({
    "Student_ID": [101,102,103,104,105,106,107,108],
    "Name": ["Arjun","Rogan","Prakash","Jothi","Mathi","Dhanush","Sanjay","Arun"],
    "Department": ["AI","ML","AI","DS","ML","DS","AI","ML"],
    "Gender": ["Female","Male","Female","Male","Female","Male","Female","Male"],
    "Marks": [95,88,91,84,89,76,98,92],
    "Age": [22,23,21,24,22,23,21,22]
})

print(students)

   Student_ID     Name Department  Gender  Marks  Age
0         101    Arjun         AI  Female     95   22
1         102    Rogan         ML    Male     88   23
2         103  Prakash         AI  Female     91   21
3         104    Jothi         DS    Male     84   24
4         105    Mathi         ML  Female     89   22
5         106  Dhanush         DS    Male     76   23
6         107   Sanjay         AI  Female     98   21
7         108     Arun         ML    Male     92   22

<h2>groupby()</h2>

groupby() is used to divide data into groups based on one or more columns.

It is similar to SQL's GROUP BY clause.

Syntax:

df.groupby("column")

__Example:__

A company calculates the average salary for each department.

<h3>AI/ML Usage</h3>
    
Used to summarize data before feature engineering and exploratory data analysis (EDA).

In [4]:
students.groupby("Department")["Marks"].mean()

Department
AI    94.666667
DS    80.000000
ML    89.666667
Name: Marks, dtype: float64

In [5]:
# Group by Multiple Columns

students.groupby(["Department","Gender"])["Marks"].mean()

Department  Gender
AI          Female    94.666667
DS          Male      80.000000
ML          Female    89.000000
            Male      90.000000
Name: Marks, dtype: float64

<h2>agg()</h2>

agg() (Aggregate) performs multiple calculations on grouped data simultaneously.

Syntax:

df.groupby("column").agg(functions)

__Example:__

A bank calculates:

<ul><li>Average balance</li>
<li>Maximum balance</li>
<li>Number of customers</li></ul>

for each branch.

AI/ML Usage
Used to generate statistical summaries of grouped features.

In [7]:
students.groupby("Department")["Marks"].agg(["mean","max","min","count"])

                 mean  max  min  count
Department
AI          94.666667   98   91      3
DS          80.000000   84   76      2
ML          89.666667   92   88      3

In [10]:
students.groupby("Department").agg({
    "Marks":["mean","max"],
    "Age":"mean"
})

                Marks            Age
                 mean max       mean
Department
AI          94.666667  98  21.333333
DS          80.000000  84  23.500000
ML          89.666667  92  22.333333

<h2>transform()</h2>

transform() performs a calculation within each group but returns a result with the same number of rows as the original DataFrame.

__Example:__

Each employee's salary is compared with the average salary of their department.

<h3>AI/ML Usage</h3>
    
Used for feature engineering by creating normalized or group-based features.

In [13]:
students["Department_Average"] = students.groupby("Department")["Marks"].transform("mean")
print(students)

   Student_ID     Name Department  Gender  Marks  Age  Department_Average
0         101    Arjun         AI  Female     95   22           94.666667
1         102    Rogan         ML    Male     88   23           89.666667
2         103  Prakash         AI  Female     91   21           94.666667
3         104    Jothi         DS    Male     84   24           80.000000
4         105    Mathi         ML  Female     89   22           89.666667
5         106  Dhanush         DS    Male     76   23           80.000000
6         107   Sanjay         AI  Female     98   21           94.666667
7         108     Arun         ML    Male     92   22           89.666667

<h2>filter()</h2>

filter() removes groups that do not satisfy a specified condition.

__Example:__

A company keeps only departments whose average sales exceed ₹1,00,000.

<h3>AI/ML Usage</h3>

Useful for removing weak or insignificant groups before analysis.

In [14]:
students.groupby("Department").filter(
    lambda x: x["Marks"].mean() > 90
)

   Student_ID     Name Department  Gender  Marks  Age  Department_Average
0         101    Arjun         AI  Female     95   22           94.666667
2         103  Prakash         AI  Female     91   21           94.666667
6         107   Sanjay         AI  Female     98   21           94.666667

<h2>Pivot Tables</h2>

A Pivot Table summarizes data by grouping rows and columns while applying aggregation functions.

It provides a spreadsheet-like summary.

Syntax:

pd.pivot_table()

__Example:__

A company creates a report showing average monthly sales for each branch.

<h3>AI/ML Usage</h3>
    
Pivot tables are useful for quickly summarizing datasets during EDA.

In [16]:
pd.pivot_table(
    students,
    values = "Marks",
    index = "Department",
    aggfunc= "mean"
)

                Marks
Department
AI          94.666667
DS          80.000000
ML          89.666667

In [17]:
# Multiple Aggregations
pd.pivot_table(
    students,
    values = "Marks",
    index = "Department",
    aggfunc = ["mean", "max", "min"]
)

                 mean   max   min
                Marks Marks Marks
Department
AI          94.666667    98    91
DS          80.000000    84    76
ML          89.666667    92    88

In [19]:
# Pivot with rows and Columns
pd.pivot_table(
    students,
    values = "Marks",
    index = "Department",
    columns = "Gender",
    aggfunc = "mean"
)

Gender         Female  Male
Department
AI          94.666667   NaN
DS                NaN  80.0
ML          89.000000  90.0

<h2>crosstab()</h2>

pd.crosstab() creates a frequency/count table between categorical variables.

It tells us how many times combinations of categories occur.

Syntax:

pd.crosstab(row,column)

__Example:__

A hospital counts male and female patients in each department.

<h3>AI/ML Usage</h3>

Used to study relationships between categorical variables before model building.

In [21]:
pd.crosstab(
    students["Department"],
    students["Gender"]
)

Gender      Female  Male
Department
AI               3     0
DS               0     2
ML               1     2

In [23]:
pd.crosstab(
    students["Department"],
    students["Gender"],
    margins=True
)

Gender      Female  Male  All
Department
AI               3     0    3
DS               0     2    2
ML               1     2    3
All              4     4    8

In [25]:
pd.crosstab(
    students["Department"],
    students["Gender"],
    normalize = True
)

Gender      Female  Male
Department
AI           0.375  0.00
DS           0.000  0.25
ML           0.125  0.25