<h1>Combining Datasets</h1>

In [1]:
import pandas as pd

<h3>Create Sample Dataset 1</h3>

In [2]:
students = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Name": ["Arjun", "Rogan", "Prakah", "Jothi"],
    "Department": ["AI", "ML", "DS", "AI"]
})

print(students)

   Student_ID    Name Department
0         101   Arjun         AI
1         102   Rogan         ML
2         103  Prakah         DS
3         104   Jothi         AI

<h3>Create Sample Dataset 2</h3>

In [3]:
marks = pd.DataFrame({
    "Student_ID": [101, 102, 103, 104],
    "Marks": [95, 88, 91, 84]
})

print(marks)

   Student_ID  Marks
0         101     95
1         102     88
2         103     91
3         104     84

<h3>Create Sample Dataset 3</h3>

In [4]:
new_students = pd.DataFrame({
    "Student_ID": [105, 106],
    "Name": ["Mathi", "Dhanush"],
    "Department": ["ML", "DS"]
})

print(new_students)

   Student_ID     Name Department
0         105    Mathi         ML
1         106  Dhanush         DS

<h2>concat()</h2>

concat() combines two or more DataFrames along rows or columns.

It is useful when datasets have a similar structure.

Syntax:

pd.concat([df1, df2])

__Example:__

Suppose a college stores student information in separate files:

<ul><li>students_january.csv</li>
<li>students_february.csv</li>
<li>students_march.csv</li></ul>

We can combine all three datasets into one DataFrame.

In [5]:
combined_students = pd.concat(
    [students, new_students],
    ignore_index = True
)
print(combined_students)

   Student_ID     Name Department
0         101    Arjun         AI
1         102    Rogan         ML
2         103   Prakah         DS
3         104    Jothi         AI
4         105    Mathi         ML
5         106  Dhanush         DS

<h3>Concatenating Columns</h3>

In [9]:
student_info = pd.DataFrame({
    "Name": ["Arjun", "Rogan", "Prakash"],
    "Age": [22, 23, 21]
})

student_scores = pd.DataFrame({
    "Marks": [95, 88, 91],
    "Grade": ["A", "B", "A"]
})

result = pd.concat(
    [student_info, student_scores],
    axis=1
)

print(result)

      Name  Age  Marks Grade
0    Arjun   22     95     A
1    Rogan   23     88     B
2  Prakash   21     91     A

<h3>AI/ML Usage</h3>

concat() is useful when combining:

<ul><li>Monthly datasets</li>
<li>Yearly datasets</li>
<li>Training datasets</li></ul>

Data collected from multiple sources

<h2>merge()</h2>

merge() combines DataFrames using one or more common columns, similar to SQL JOIN operations.

Syntax:

pd.merge(df1, df2, on="column")

__Example:__

Suppose a college stores, Student information and marks separately:

<ul><li>Student_ID | Name | Department</li>
<li>Student_ID | Marks</li></ul>

We can combine them using Student_ID.

In [10]:
merged_data = pd.merge(
    students,
    marks,
    on="Student_ID"
)

print(merged_data)

   Student_ID    Name Department  Marks
0         101   Arjun         AI     95
1         102   Rogan         ML     88
2         103  Prakah         DS     91
3         104   Jothi         AI     84

<h3>Types of Merge</h3>

Pandas supports:

<ul><li>Inner Join</li>
<li>Left Join</li>
<li>Right Join</li>
<li>Outer Join</li></ul>
    
<h3>Inner Join</h3>

Returns only matching records.

In [14]:
pd.merge(
    students,
    marks,
    on = "Student_ID",
    how= "inner"
)

   Student_ID    Name Department  Marks
0         101   Arjun         AI     95
1         102   Rogan         ML     88
2         103  Prakah         DS     91
3         104   Jothi         AI     84

<h3>Left Join</h3>

Keeps all rows from the left DataFrame.

In [15]:
pd.merge(
    students,
    marks,
    on="Student_ID",
    how = "left"
)

   Student_ID    Name Department  Marks
0         101   Arjun         AI     95
1         102   Rogan         ML     88
2         103  Prakah         DS     91
3         104   Jothi         AI     84

<h3>Right Join</h3>

Keeps all rows from the right DataFrame.

In [16]:
pd.merge(
    students,
    marks,
    on = "Student_ID",
    how = "right"
)

   Student_ID    Name Department  Marks
0         101   Arjun         AI     95
1         102   Rogan         ML     88
2         103  Prakah         DS     91
3         104   Jothi         AI     84

<h3>Outer Join</h3>

Keeps all rows from both DataFrames.

In [17]:
pd.merge(
    students,
    marks,
    on = "Student_ID",
    how = "outer"
)

   Student_ID    Name Department  Marks
0         101   Arjun         AI     95
1         102   Rogan         ML     88
2         103  Prakah         DS     91
3         104   Jothi         AI     84

<h3>AI/ML Usage</h3>

merge() is extremely important when combining features from different datasets.

<h2>join()</h2>

join() combines DataFrames using their index by default.

It is particularly useful when the DataFrames have matching indexes.

__Example:__

A company may have, Employee information and Employee performance :

If Employee_ID is already used as the index, join() can combine the datasets easily.

In [27]:
students_info = pd.DataFrame({
    "Name":["Arjun","Rogan","Prakash"],
    "Department":["AI","ML","DS"]
},index=[101,102,103])

students_marks = pd.DataFrame({
    "Marks":[95,87,90]
},index=[101,102,103])

In [28]:
result = students_info.join(students_marks)
print(result)

        Name Department  Marks
101    Arjun         AI     95
102    Rogan         ML     87
103  Prakash         DS     90

<h3>Types of Joins</h3>

In [29]:
# Left Join
students_info.join(
    students_marks,
    how="left"
)

        Name Department  Marks
101    Arjun         AI     95
102    Rogan         ML     87
103  Prakash         DS     90

In [31]:
# Inner Join
students_info.join(
    students_marks,
    how="inner"
)

        Name Department  Marks
101    Arjun         AI     95
102    Rogan         ML     87
103  Prakash         DS     90

<h3>AI/ML Usage</h3>

join() can be useful when feature datasets are indexed using a common identifier.

<h2>append() — Deprecation and Alternative</h2>

append() was previously used to add rows from one DataFrame to another.

Older Pandas Code:

df1.append(df2)

However, DataFrame.append() was deprecated in Pandas 1.4 and removed in Pandas 2.0.

Therefore, we should not use append() in modern Pandas.

Old Code:

result = students.append(new_students)

--> Old approach - do not use in modern Pandas

This may produce:

AttributeError: 'DataFrame' object has no attribute 'append'

Why was append() removed?

concat() is more flexible and efficient for combining multiple DataFrames.

Instead of:

df1.append(df2)

use:

pd.concat([df1, df2])

In [32]:
# Modern Alternative: concat()

result = pd.concat(
    [students, new_students],
    ignore_index=True
)

print(result)

   Student_ID     Name Department
0         101    Arjun         AI
1         102    Rogan         ML
2         103   Prakah         DS
3         104    Jothi         AI
4         105    Mathi         ML
5         106  Dhanush         DS

<h3>AI/ML Usage:</h3>

When new batches of training data arrive, use concat() to combine them with existing data.

<h2>combine_first()</h2>

combine_first() fills missing values in one DataFrame using values from another DataFrame.

It is particularly useful when two datasets contain partial information.

In [33]:
# Create Sample Data

student_data1 = pd.DataFrame({
    "Name": ["Arjun", "Rogan", "Prakasj"],
    "Marks": [95, None, 91]
})

student_data2 = pd.DataFrame({
    "Name": ["Arjun", "Rogan", "Prakash"],
    "Marks": [None, 88, 92]
})

In [34]:
result = student_data1.combine_first(student_data2)
print(result)

      Name  Marks
0    Arjun   95.0
1    Rogan   88.0
2  Prakasj   91.0

What happened?

student_data1 had:

Aishu 95

Rahul NaN

Priya 91

student_data2 had:

Aishu NaN

Rahul 88

Priya 92

combine_first() keeps the value from the first DataFrame whenever it exists.

If the first DataFrame has a missing value, it takes the value from the second DataFrame.

Example:

A hospital has patient information from two systems:

System A

Patient 101 → Age = 25

Patient 102 → Age = Missing

System B

Patient 101 → Age = 25

Patient 102 → Age = 32

combine_first() can fill the missing age from System B.

<h3>AI/ML Usage</h3>

Useful when combining datasets from different sources and filling missing feature values.